[[redirects]]
  from = "/"
  to = "https://newsapi.org/v2/everything?q=Apple&from=2021-07-25&sortBy=popularity"
  status = 200
  force = true
  signed = "REACT_APP_API_KEY"

  {
  "netlify_id": "2597ba35-6f5d-4f2c-a620-a3aa8691ae2f",
  "site_url": "https://my-api-website.netlify.app/",
  "context": "the deploy context for this request"
}